server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: sugon@123456
        url: jdbc:mysql://172.16.10.12:3306/idrb_platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        # 修改默认的javax.sql.DataSource为阿里天池提供的
        type: com.alibaba.druid.pool.DruidDataSource
        # 用户信息数据表名
        table: account
        # druid 数据源专有配置
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

nginx:
    host: 172.16.10.12
    confdir: /etc/nginx/conf.d/tools
    temp: /config/nginx.temp

redis:
    host: 172.16.10.12
    port: 6379
    password: idrb@sugon

jsonconfig: /config/settings.json
 